<?php

namespace AppBundle\Repository;

/**
 * ArtisticCurrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisticCurrentRepository extends \Doctrine\ORM\EntityRepository
{
}
