<?php

namespace AppBundle\Repository;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends \Doctrine\ORM\EntityRepository
{
//    public function seenArtists ($user)
//    {
//        return $this->createQueryBuilder('a')
//            ->join('a.artworks', 'a')
//            ->join('a.users', 'u')
//            ->where('u.id = :user ')
//            ->setParameter('user', $user)
//            ->getQuery()
//            ->getResult();
//    }
}
