<?php

namespace AppBundle\Repository;

/**
 * ArtisticCurrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisticCurrentRepository extends \Doctrine\ORM\EntityRepository
{
    public function seenCurrents ($user)
    {
        return $this->createQueryBuilder('ac')
            ->join('ac.artworks', 'a')
            ->join('a.users', 'u')
            ->where('u.id = :user ')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
