<?php
/**
 * Created by PhpStorm.
 * User: wilder17
 * Date: 14/06/18
 * Time: 14:20
 */

namespace AppBundle\Repository;


use AppBundle\Entity\ArtisticCurrent;
use AppTestBundle\Entity\FunctionalTests\User;

/**
 * ArtworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkRepository extends \Doctrine\ORM\EntityRepository
{
    public function seenArtworksInOneCurrent($user, $current)
    {
        return $this->createQueryBuilder('ar')
            ->where('ar.users = :user')
            ->setParameter('user', $user)
            ->andWhere('ar.current = :current')
            ->setParameter('current', $current)
            ->getQuery()
            ->getResult();
    }
}

