<?php
/**
 * Created by PhpStorm.
 * User: wilder17
 * Date: 14/06/18
 * Time: 14:20
 */

namespace AppBundle\Repository;

use AppBundle\Entity\ArtisticCurrent;
use AppTestBundle\Entity\FunctionalTests\User;

/**
 * ArtworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkRepository extends \Doctrine\ORM\EntityRepository
{
    public function seenArtworksInOneCurrent($user, $current)
    {
        return $this->createQueryBuilder('ar')
            ->join('ar.users', 'u')
            ->where('u.id = :user ')
            ->setParameter('user', $user)
            ->join('ar.current', 'c')
            ->andWhere('c.name = :current')
            ->setParameter('current', $current)
            ->getQuery()
            ->getResult();
    }

    public function seenArtworksNbInOneCurrent($user, $current)
    {
        return $this->createQueryBuilder('ar')
            ->select('count(ar.id)')
            ->join('ar.users', 'u')
            ->where('u.id = :user ')
            ->setParameter('user', $user)
            ->join('ar.current', 'c')
            ->andWhere('c.name = :current')
            ->setParameter('current', $current)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findAllInOneCurrent($current)
    {
        return $this->createQueryBuilder('ar')
            ->join('ar.current', 'c')
            ->andWhere('c.name = :current')
            ->setParameter('current', $current)
            ->getQuery()
            ->getResult();
    }
}
