<?php

namespace AppBundle\Repository;

/**
 * WorkOfArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkOfArtRepository extends \Doctrine\ORM\EntityRepository
{
}
